import { Website } from "./types"

export const defaultTitle = "Generation Alpha"

export const sections = [
  {
    title: "Entertainment",
    websites: [
      { name: "YouTube", url: "https://www.youtube.com", description: "Videos and livestreams" },
      { name: "Netflix", url: "https://www.netflix.com", description: "Watch movies and TV shows" },
      { name: "Disney+", url: "https://www.disneyplus.com", description: "Disney movies and Marvel shows" },
      { name: "Spotify", url: "https://www.spotify.com", description: "Music and podcasts" },
      { name: "Twitch", url: "https://www.twitch.tv", description: "Gaming livestreams" },
      { name: "Crunchyroll", url: "https://www.crunchyroll.com", description: "Anime streaming" },
      { name: "Hulu", url: "https://www.hulu.com", description: "TV shows and movies" },
      { name: "Tubi", url: "https://tubitv.com", description: "Free movies and shows" },
      { name: "Pluto TV", url: "https://pluto.tv", description: "Free live TV" },
      { name: "Prime Video", url: "https://www.primevideo.com", description: "Movies and shows" },
    ],
  },
  {
    title: "Social Media",
    websites: [
      { name: "TikTok", url: "https://www.tiktok.com", description: "Watch viral short videos" },
      { name: "Instagram", url: "https://www.instagram.com", description: "Photos and reels" },
      { name: "Snapchat", url: "https://www.snapchat.com", description: "Chat and stories" },
      { name: "Discord", url: "https://www.discord.com", description: "Chat with friends" },
      { name: "Reddit", url: "https://www.reddit.com", description: "Communities and discussions" },
      { name: "Pinterest", url: "https://www.pinterest.com", description: "Ideas and inspiration" },
      { name: "ChatGPT", url: "https://chatgpt.com", description: "AI assistant" },
    ],
  },
  {
    title: "Games",
    websites: [
      { name: "Roblox", url: "https://www.roblox.com", description: "Millions of online games" },
      { name: "Minecraft", url: "https://www.minecraft.net", description: "Build and explore worlds" },
      { name: "Fortnite", url: "https://www.fortnite.com", description: "Battle royale and creative mode" },
      { name: "Call of Duty Mobile", url: "https://apps.apple.com/us/app/call-of-duty-mobile/id1287282214", description: "Mobile shooter game" },
      { name: "PUBG Mobile", url: "https://apps.apple.com/us/app/pubg-mobile/id1330123889", description: "Battle royale survival" },
      { name: "Brawl Stars", url: "https://apps.apple.com/us/app/brawl-stars/id1229016807", description: "Fast multiplayer battles" },
      { name: "Clash Royale", url: "https://apps.apple.com/us/app/clash-royale/id1053012308", description: "Real-time strategy battles" },
      { name: "Clash of Clans", url: "https://apps.apple.com/us/app/clash-of-clans/id529479190", description: "Build villages and battle" },
      { name: "Among Us", url: "https://apps.apple.com/us/app/among-us/id1351168404", description: "Find the impostor" },
      { name: "Stumble Guys", url: "https://apps.apple.com/us/app/stumble-guys/id1541153375", description: "Funny obstacle races" },
      { name: "Subway Surfers", url: "https://apps.apple.com/us/app/subway-surfers/id512939461", description: "Classic endless runner" },
      { name: "Temple Run 2", url: "https://apps.apple.com/us/app/temple-run-2/id572395608", description: "Escape and survive" },
      { name: "Pokémon GO", url: "https://apps.apple.com/us/app/pokémon-go/id1094591345", description: "Catch Pokémon outside" },
      { name: "Geometry Dash Lite", url: "https://apps.apple.com/us/app/geometry-dash-lite/id698255242", description: "Free Geometry Dash version" },
      { name: "Geometry Dash World", url: "https://apps.apple.com/us/app/geometry-dash-world/id1185457891", description: "Explore Geometry Dash levels" },
      { name: "Geometry Dash Meltdown", url: "https://apps.apple.com/us/app/geometry-dash-meltdown/id1045901853", description: "Rhythm platform challenge" },
      { name: "Geometry Dash SubZero", url: "https://apps.apple.com/us/app/geometry-dash-subzero/id1324044770", description: "Music and jumping action" },
      { name: "Free Fire", url: "https://ff.garena.com", description: "Battle royale action game" },
      { name: "Rocket League", url: "https://www.rocketleague.com", description: "Soccer with rocket cars" },
      { name: "Valorant", url: "https://playvalorant.com", description: "Competitive tactical shooter" },
      { name: "League of Legends", url: "https://www.leagueoflegends.com", description: "Popular MOBA strategy game" },
      { name: "Genshin Impact", url: "https://genshin.hoyoverse.com", description: "Open world anime adventure" },
      { name: "Fall Guys", url: "https://www.fallguys.com", description: "Funny obstacle survival game" },
      { name: "Apex Legends", url: "https://www.ea.com/games/apex-legends", description: "Squad battle royale shooter" },
      { name: "CS2", url: "https://www.counter-strike.net", description: "Competitive FPS action" },
      { name: "Halo Infinite", url: "https://www.halowaypoint.com", description: "Sci-fi multiplayer battles" },
      { name: "FIFA", url: "https://www.ea.com/games/ea-sports-fc", description: "Football and soccer simulation" },
      { name: "NBA 2K", url: "https://nba.2k.com", description: "Basketball sports game" },
    ],
  },
  {
    title: "Editing Apps",
    websites: [
      { name: "CapCut", url: "https://www.capcut.com", description: "Edit viral videos" },
      { name: "Canva", url: "https://www.canva.com", description: "Create graphics and slides" },
      { name: "Adobe Photoshop", url: "https://www.adobe.com/products/photoshop.html", description: "Professional photo editing" },
      { name: "Photopea", url: "https://www.photopea.com", description: "Free Photoshop alternative" },
      { name: "Pixlr", url: "https://pixlr.com", description: "Online photo editor" },
      { name: "Figma", url: "https://www.figma.com", description: "Design websites and apps" },
    ],
  },
  {
    title: "School",
    websites: [
      { name: "Google Classroom", url: "https://classroom.google.com", description: "Assignments and school classes" },
      { name: "Blooket", url: "https://www.blooket.com", description: "Fun classroom quiz games" },
      { name: "Classroom 6x", url: "https://classroom6x.org", description: "Popular unblocked games website" },
      { name: "Classroom Resources", url: "https://sites.google.com/view/classroom-resources", description: "Unblocked games and resources" },
      { name: "Cool Math Games", url: "https://www.coolmathgames.com", description: "Educational puzzle games" },
      { name: "Khan Academy", url: "https://www.khanacademy.org", description: "Free learning and lessons" },
      { name: "Quizlet", url: "https://quizlet.com", description: "Flashcards and study tools" },
      { name: "Kahoot!", url: "https://kahoot.com", description: "Interactive classroom quizzes" },
      { name: "Duolingo", url: "https://www.duolingo.com", description: "Learn languages for free" },
    ],
  },
  {
    title: "Fun Websites",
    websites: [
      { name: "Neal.fun", url: "https://neal.fun", description: "Fun internet experiments" },
      { name: "GeoGuessr", url: "https://www.geoguessr.com", description: "Guess places around the world" },
      { name: "Akinator", url: "https://en.akinator.com", description: "Guess characters and people" },
      { name: "The Useless Web", url: "https://theuselessweb.com", description: "Random funny websites" },
      { name: "Pointer Pointer", url: "https://pointerpointer.com", description: "Finds a photo pointing at your cursor" },
      { name: "Quick, Draw!", url: "https://quickdraw.withgoogle.com", description: "AI guessing drawing game" },
      { name: "Chrome Music Lab", url: "https://musiclab.chromeexperiments.com", description: "Create music with fun tools" },
      { name: "Little Alchemy 2", url: "https://littlealchemy2.com", description: "Mix elements to create things" },
    ],
  },
]

export const secretApps: Website[] = [
  { name: "Scratch", url: "https://scratch.mit.edu", description: "Create games and animations" },
  { name: "Replit", url: "https://replit.com", description: "Code in your browser" },
  { name: "CodePen", url: "https://codepen.io", description: "Build frontend demos" },
  { name: "Desmos", url: "https://www.desmos.com", description: "Graphing calculator" },
  { name: "Remove.bg", url: "https://www.remove.bg", description: "Remove image backgrounds" },
  { name: "Notion", url: "https://www.notion.so", description: "Notes and organization" },
  { name: "Trello", url: "https://trello.com", description: "Project boards" },
  { name: "Giphy", url: "https://giphy.com", description: "GIF search" },
  { name: "Tenor", url: "https://tenor.com", description: "Reaction GIFs" },
  { name: "Sketchpad", url: "https://sketch.io/sketchpad", description: "Draw online" },
  { name: "Miro", url: "https://miro.com", description: "Whiteboard app" },
  { name: "Soundtrap", url: "https://www.soundtrap.com", description: "Make music online" },
  { name: "Grammarly", url: "https://www.grammarly.com", description: "Writing assistant" },
  { name: "BeReal", url: "https://bereal.com", description: "Social photo app" },
  { name: "Threads", url: "https://www.threads.net", description: "Social app" },
]

export const secretWebsites: Website[] = [
  { name: "Bored Button", url: "https://www.boredbutton.com", description: "Random fun websites" },
  { name: "Hacker Typer", url: "https://hackertyper.net", description: "Fake hacker typing" },
  { name: "Zoom Quilt", url: "https://zoomquilt.org", description: "Infinite zoom art" },
  { name: "WeaveSilk", url: "https://weavesilk.com", description: "Interactive silk art" },
  { name: "Find the Invisible Cow", url: "https://findtheinvisiblecow.com", description: "Funny sound game" },
  { name: "MapCrunch", url: "https://www.mapcrunch.com", description: "Random street views" },
  { name: "Sandspiel", url: "https://sandspiel.club", description: "Falling sand game" },
  { name: "FutureMe", url: "https://www.futureme.org", description: "Write future letters" },
  { name: "Astronaut.io", url: "https://astronaut.io", description: "Random YouTube videos" },
  { name: "Internet Live Stats", url: "https://www.internetlivestats.com", description: "Live internet stats" },
  { name: "Mental Floss", url: "https://www.mentalfloss.com", description: "Facts and trivia" },
  { name: "Emoji Kitchen", url: "https://emoji.supply/kitchen", description: "Mix emojis" },
  { name: "Scream Into the Void", url: "https://screamintothevoid.com", description: "Type and release thoughts" },
  { name: "Radiooooo", url: "https://radiooooo.com", description: "Music by country and decade" },
  { name: "Bouncy Balls", url: "https://bouncyballs.org", description: "Noise visualizer" },
]